# Generated by Django 3.2.9 on 2021-12-01 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_operador', models.BigIntegerField()),
                ('id_vehículo', models.BigIntegerField()),
                ('fecha_entrada', models.DateTimeField(auto_now_add=True)),
                ('fecha_salida', models.DateTimeField(auto_now_add=True)),
                ('costo', models.IntegerField(default=0)),
                ('id_plaza', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Plaza',
            fields=[
                ('idPlaza', models.BigAutoField(primary_key=True, serialize=False)),
                ('isAvailible', models.BooleanField(default=True)),
                ('tipo', models.CharField(max_length=7)),
            ],
        ),
    ]
