# Generated by Django 3.2.9 on 2021-12-02 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_factura', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plaza',
            old_name='isAvailible',
            new_name='isAvailable',
        ),
    ]
