# Generated by Django 3.2.9 on 2021-12-02 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_factura', '0002_rename_isavailible_plaza_isavailable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plaza',
            old_name='idPlaza',
            new_name='id',
        ),
    ]
