# Generated by Django 3.2.9 on 2021-12-02 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_factura', '0003_rename_idplaza_plaza_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='id_plaza',
        ),
        migrations.AddField(
            model_name='factura',
            name='plaza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_factura.plaza'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_salida',
            field=models.DateTimeField(blank=True),
        ),
    ]
