# Generated by Django 3.2.9 on 2021-12-02 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_factura', '0004_auto_20211201_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fecha_salida',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='plaza',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app_factura.plaza'),
            preserve_default=False,
        ),
    ]
