# Generated by Django 3.2.9 on 2021-12-04 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_factura', '0006_alter_factura_plaza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plaza',
            name='tipo',
        ),
    ]
